# Generated by Django 4.0.6 on 2022-07-13 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('BlogId', models.AutoField(primary_key=True, serialize=False)),
                ('BlogName', models.CharField(max_length=500)),
                ('BlogContent', models.CharField(max_length=2000)),
                ('BlogTag', models.CharField(max_length=500)),
                ('PostDate', models.DateField()),
                ('BlogUserId', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('UserId', models.AutoField(primary_key=True, serialize=False)),
                ('UserName', models.CharField(max_length=500)),
            ],
        ),
    ]
